#spring.application.name=UberProject-BookingService
#
#spring.datasource.url= jdbc:mysql://localhost:3306/Uber_Db_Local
#
#spring.datasource.username= root
#
#spring.datasource.password=madhu@340
#
#spring.jpa.show-sql=true
#
#spring.jpa.hibernate.ddl-auto=validate
#
#server.port=7000


spring:
  application:
    name: UberProject-BookingService
  datasource:
    url:  jdbc:mysql://localhost:3306/Uber_Db_Local
    username: root
    password: madhu@340
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

server:
  port: 7000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

